MACOSX_DEPLOYMENT_TARGET: '10.10'
python:
  - 3.10
  - 3.11
numpy:
  - 1.25.*
  - 1.25.*
zip_keys:
  - python
  - numpy
c_compiler:
  - vs2019 # [win]
  - clang # [osx]
  - gcc  # [linux]
cxx_compiler:
  - vs2019 # [win]
  - clangxx # [osx]
  - gxx # [linux]
fortran_compiler:
  - gfortran # [linux]

CONDA_BUILD_SYSROOT:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk

