MACOSX_DEPLOYMENT_TARGET: '12'
python:
  - 3.11
numpy:
  - 2.4.*

zip_keys:
  - python
  - numpy

c_compiler:
  - vs2022 # [win]
  - clang # [osx]
  - gcc  # [linux]
cxx_compiler:
  - vs2022 # [win]
  - clangxx # [osx]
  - gxx # [linux]
