MACOSX_DEPLOYMENT_TARGET: '10.10'
python:
    - 3.7
    - 3.8
    - 3.9
    - 3.10
numpy:
  - 1.20
c_compiler:
  - vs2019   # [win]
  - clang # [osx]
  - gcc  # [linux]
cxx_compiler:
  - vs2019   # [win]
  - clangxx # [osx]
  - gxx # [linux]
c_compiler_version:
  - 7.5.0  # [linux]
cxx_compiler_version:
  - 7.5.0  # [linux]
CONDA_BUILD_SYSROOT:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk

