package:
    name: opensim
    version: "4.0.0"

source:
    fn: OpenSim-40-source.zip
    url: https://github.com/opensim-org/opensim-core/archive/v4.0.0_alpha.zip
    sha256: dd425e886f394098533142652e246b375c8fb4d69246f0ffffcdd63bbbdb39c3

build:
    number: 1
    # NOTE : For C++11 builds, vc14/VS 2015 are the only acceptable targets
    # which only Python 3.5 supports. So skip previous Python versions.
    # skip: true                # [win and not py35]
    features:
        - vc14                # [win and py35]
    # NOTE : This is needed to ensure the paths to Simbody's binaries, like
    # simbody-visualizer, are corrected.
    detect_binary_files_with_prefix: true

requirements:
    build:
        - toolchain
        - cmake >=2.8.6
        - python                  # [win]

about:
    home: http://opensim.stanford.edu
    license: Apache-2.0
    summary: >
        OpenSim is software that lets users develop models of musculoskeletal
        structures and create dynamic simulations of movement.

extra:
    recipe-maintainers:
        - kidzik
