{% set version = "4.4" %}

package:
    name: opensim
    version: {{ version }}

source:
    git_url: https://github.com/opensim-org/opensim-core.git
    git_rev: branch_4.4_conda
build:
    number: 2
    # NOTE : For C++11 builds, vc16/VS 2019 are the only acceptable targets
    features:
        - vc16                # [win and py39]
    # NOTE : This is needed to ensure the paths to Simbody's binaries, like
    # simbody-visualizer, are corrected.
    detect_binary_files_with_prefix: true
    string: py{{ CONDA_PY }}np{{ CONDA_NPY }}
requirements:
    host:
        - openblas # [not win]
    build:
        - toolchain 2.4.0 0     # [win]
        #- wheel 0.36.2 pyhd3eb1b0_0
        - swig 4.0.2
        - cmake >=3.15,<3.25
        - numpy {{ numpy }}
        - python {{ python }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - openblas # [not win]
        - make # [not win]

    run:
        - numpy {{ numpy }}
        - python {{ python }}
        - freeglut # [win]
        - openblas # [not win]

test:
  # imports:
  #  - opensim
    
about:
    home: http://opensim.stanford.edu
    license: Apache-2.0
    summary: >
        OpenSim is software that lets users develop models of musculoskeletal
        structures and create dynamic simulations of movement.

extra:
    recipe-maintainers:
        - aymanhab
        - AlbertoCasasOrtiz
        - kidzik
