package:
    name: opensim
    version: "4.3.1"

source:
    git_url: https://github.com/opensim-org/opensim-core.git
    git_rev: "7fda7b766b9fc0920c6e099a58c63f66a31662f0"
  
build:
    number: 0
    # NOTE : For C++11 builds, vc16/VS 2019 are the only acceptable targets
    features:
        - vc16                # [win and py39]
    # NOTE : This is needed to ensure the paths to Simbody's binaries, like
    # simbody-visualizer, are corrected.
    detect_binary_files_with_prefix: true
    string: py{{ CONDA_PY }}np{{ CONDA_NPY }}
requirements:
    build:
        - toolchain 2.4.0 0
        - wheel 0.36.2 pyhd3eb1b0_0
        - swig
        - cmake >=3.15
        - numpy {{ numpy }}
        - python {{ python }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}

    run:
        - python
        - numpy
        - freeglut

test:
  # imports:
  #  - opensim
    
about:
    home: http://opensim.stanford.edu
    license: Apache-2.0
    summary: >
        OpenSim is software that lets users develop models of musculoskeletal
        structures and create dynamic simulations of movement.

extra:
    recipe-maintainers:
        - aymanhab
        - kidzik
